# Fromprefecture.create(name: '北海道')
# Fromprefecture.create(name: '青森県')
# Fromprefecture.create(name: '岩手県')
# Fromprefecture.create(name: '宮城県')
# Fromprefecture.create(name: '秋田県')
# Fromprefecture.create(name: '山形県')
# Fromprefecture.create(name: '福島県')
# Fromprefecture.create(name: '茨城県')
# Fromprefecture.create(name: '栃木県')
# Fromprefecture.create(name: '群馬県')
# Fromprefecture.create(name: '埼玉県')
# Fromprefecture.create(name: '千葉県')
# Fromprefecture.create(name: '東京都')
# Fromprefecture.create(name: '神奈川県')
# Fromprefecture.create(name: '新潟県')
# Fromprefecture.create(name: '富山県')
# Fromprefecture.create(name: '石川県')
# Fromprefecture.create(name: '福井県')
# Fromprefecture.create(name: '山梨県')
# Fromprefecture.create(name: '長野県')
# Fromprefecture.create(name: '岐阜県')
# Fromprefecture.create(name: '静岡県')
# Fromprefecture.create(name: '愛知県')
# Fromprefecture.create(name: '三重県')
# Fromprefecture.create(name: '滋賀県')
# Fromprefecture.create(name: '京都府')
# Fromprefecture.create(name: '大阪府')
# Fromprefecture.create(name: '兵庫県')
# Fromprefecture.create(name: '奈良県')
# Fromprefecture.create(name: '和歌山県')
# Fromprefecture.create(name: '鳥取県')
# Fromprefecture.create(name: '島根県')
# Fromprefecture.create(name: '岡山県')
# Fromprefecture.create(name: '広島県')
# Fromprefecture.create(name: '山口県')
# Fromprefecture.create(name: '徳島県')
# Fromprefecture.create(name: '香川県')
# Fromprefecture.create(name: '愛媛県')
# Fromprefecture.create(name: '高知県')
# Fromprefecture.create(name: '福岡県')
# Fromprefecture.create(name: '佐賀県')
# Fromprefecture.create(name: '長崎県')
# Fromprefecture.create(name: '熊本県')
# Fromprefecture.create(name: '大分県')
# Fromprefecture.create(name: '宮崎県')
# Fromprefecture.create(name: '鹿児島県')
# Fromprefecture.create(name: '沖縄県')


# Shipping.create(name: '普通郵便(定形、定形外)')
# Shipping.create(name: 'ゆうゆうメルカリ便')

# Paydelibery.create(name: '送料込み(出品者負担)')
# Paydelibery.create(name: '着払い(購入者負担)')

# Condition.create(name: '新品、未使用')
# Condition.create(name: '未使用に近い')
# Condition.create(name: '目立った傷や汚れなし')
# Condition.create(name: 'やや傷や汚れなし')
# Condition.create(name: '傷や汚れあり')
# Condition.create(name: '全体的に状態が悪い')


# Size.create(name: 'XXS以下')
# Size.create(name: 'XS (SS)')
# Size.create(name: 'S')
# Size.create(name: 'M')
# Size.create(name: 'L')
# Size.create(name: 'XL (LL)')
# Size.create(name: '2XL (3L)')
# Size.create(name: '3XL (4L)')
# Size.create(name: '4XL (5L)')

# Term.create(name: '1~2日で発送')
# Term.create(name: '2~3日で発送')
# Term.create(name: '4~7日で発送')